### ISSUE TITLE
Integration stopped loading after the latest update

### ISSUE THREAD

**Issue by ShonP40** [hristo-atanasov/Tasmota-IRHVAC#147]
Just getting this error

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/tasmota_irhvac/climate.py", line 421, in async_setup_platform
    tasmotaIrhvac = TasmotaIrhvac(
                    ^^^^^^^^^^^^^^
  File "/config/custom_components/tasmota_irhvac/climate.py", line 568, in __init__
    self._attr_swing_modes[0]
    ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

Here’s my config:

```yaml
climate:
  - platform: tasmota_irhvac
    name: "First Floor A/C"
    unique_id: "first_floor_a_c"
    command_topic: "cmnd/tasmota_first_floor_a_c/irhvac"
    state_topic: "tele/tasmota_first_floor_a_c/RESULT"
    temperature_sensor: sensor.first_floor_a_c_bme280_temperature
    humidity_sensor: sensor.first_floor_a_c_bme280_humidity
    vendor: "AIRWELL"
    target_temp: 24 #optional - default 26 int value
    min_temp: 16 #optional - default 16 int value
    max_temp: 30 #optional - default 32 int value
    initial_operation_mode: "off" # optional - default "off" string value (one of the "supported_modes")
    precision: 1 #optional - default 1 int or float value. Can be set to 1, 0.5 or 0.1
    supported_modes:
      - "heat"
      - "cool"
      - "dry"
      - "fan_only" # Use "fan_only" even if Tasmota shows "Mode":"Fan"
      - "auto"
      - "off" #Turns the AC off - Should be in quotes
    supported_fan_speeds:
      - "min"
      - "medium"
      - "max"
      - "auto"
    supported_swing_list: []
    default_quiet_mode: "Off" #optional - default "Off" string value
    default_turbo_mode: "Off" #optional - default "Off" string value
    default_econo_mode: "Off" #optional - default "Off" string value
    hvac_model: "-1" #optional - default "1" string value
    celsius_mode: "On" #optional - default "On" string value
    default_light_mode: "Off" #optional - default "Off" string value
    default_filter_mode: "Off" #optional - default "Off" string value
    default_clean_mode: "Off" #optional - default "Off" string value
    default_beep_mode: "Off" #optional - default "Off" string value
    default_sleep_mode: "-1" #optional - default "-1" string value
    keep_mode_when_off: True #optional - default False boolean value : Must be True for MITSUBISHI_AC, ECOCLIM, etc.
```

This is a mini central A/C unit, so it doesn’t have any motors for swinging the vents, which is why I disabled it (it worked on the older versions of this integration)

**Comment by bilogic** [comment]
@nao-pon can help? Thank you.

**Comment by nao-pon** [comment]
@bilogic Thanks for reporting it! I fixed it on #148. 👍

**Comment by bilogic** [comment]
Hmm a release gets updated in my HA immediately, correct?

As a test, I just upgraded to 2024.6.4, but my issue persists, reported in #149 thanks!
