### ISSUE TITLE
Home Assistant switches Midea unit to SC mode

### ISSUE THREAD

**Issue by bkcberry** [hristo-atanasov/Tasmota-IRHVAC#82]
I am on the latest release from here, and HA  2021.12.4. When i try to use HA to change the AC set point or turn it on or off, most of the time it just switches to self clean mode, but sometimes if try it several times it will start working. Config below, any ideas?

```
  - platform: tasmota_irhvac
    name: Playroom AC
    command_topic: "cmnd/playroom/irhvac"
    state_topic: "tele/playroom/RESULT"
    #temperature_sensor: sensor.kitchen_temperature #optional this sensor is used to display current temp on the AC card
    protocol: "MIDEA"
    min_temp: 67 #optional - default 16 int value
    max_temp: 74 #optional - default 32 int value
    #default_clean_mode: "Off"
    target_temp: 72 #optional - default 26 int value
    initial_operation_mode: "off" # optional - default "off" string value
    away_temp: 74 #optional - default 24 int value
    precision: 1.0 #optional - default 1.0 float value
    supported_modes:
      - heat
      - cool
      #- dry
      - fan_only
      - auto
      - "off" #Turns the AC off - Should be quoted and should be always included here
    supported_fan_speeds:
      #- low
      #- max
      #- medium
      # - high
      #- middle
      #- focus
      #- diffuse
      #- min
      - auto
    supported_swing_list:
      - "off"
      - vertical #up to down
      #- horizontal # Left to right - remove if your AC does not support it
      #- both # remove if your AC does not support horizontal
    default_quiet_mode: "Off" #optional - default "Off" string value
    default_turbo_mode: "Off" #optional - default "Off" string value
    default_econo_mode: "Off" #optional - default "Off" string value
    hvac_model: "-1" #optional - default "1" string value
    celsius_mode: "Off" #optional - default "On" string value
    default_light_mode: "Off" #optional - default "Off" string value
    default_filter_mode: "Off" #optional - default "Off" string value
    default_clean_mode: "Off" #optional - default "Off" string value
    default_beep_mode: "Off" #optional - default "Off" string value
    default_sleep_mode: "-1" #optional - default "-1" string value

```

**Comment by nao-pon** [comment]
First of all you need to check if your unit is supported by [IRremoteESP8266](https://github.com/crankyoldgit/IRremoteESP8266).

**Comment by jbrandek** [comment]
Im having same issue it sends the command to the ac but it turn the ac into sc mode and if you change the temp it turns off the ac
Its a Carrier AC with Midea Protocol

**Comment by mattbeaton** [comment]
It looks like this was a known issue and has been solved in IRremoteESP8266 here https://github.com/crankyoldgit/IRremoteESP8266/pull/1959

Although I'm having a hard time figuring out the toolchain required to compile it into a new Tasmota firmware

**Comment by jbrandek** [comment]
I changed that device to esphome and its working fine the midea A/C, I prefer this integration as you can send a whole command, with the esp you need to set all apart, like fan speed and temp will be two commands
But for now its working with esphome...

**Comment by jbrandek** [comment]
> It looks like this was a known issue and has been solved in IRremoteESP8266 here [crankyoldgit/IRremoteESP8266#1959](https://github.com/crankyoldgit/IRremoteESP8266/pull/1959)
> 
> Although as it doesn't seem to be in a release yet, I'm assuming it'll need to be compiled manually into a new Tasmota-IR firmware, and I'm having a hard time figuring out the toolchain required to do that.

tried with tasmota ir 12.5.0 and the problem is still there, let me know if you make a custom firmware that works please

**Comment by jbrandek** [comment]
ok I made a custom firmware and its working, don't know why yet but its not updating the tele commands from the remote on HA but i can control the Midea AC

Attached if anyone needs it (Im not an expert, just followed a youtube video to make it)
[tasmota-ir-midea.bin.gz](https://github.com/hristo-atanasov/Tasmota-IRHVAC/files/11828993/tasmota-ir-midea.bin.gz)

**Comment by jbrandek** [comment]
@hristo-atanasov i think you can close this, it has been fixed in tasmota 13.1.0

**Comment by nao-pon** [comment]
@jbrandek Thanks for confirming!
